// Auth
export interface DiscordUser {
  id: string;
  username: string;
  discriminator: string;
  avatar: string | null;
  email: string;
}

export type Tier = "free" | "pro" | "elite";

export interface UserProfile {
  id: string;
  discordId: string;
  username: string;
  avatar: string | null;
  tier: Tier;
  roles: string[];
}

// Signals
export type SignalType = "buy" | "sell" | "hold";

export interface Signal {
  id: string;
  pair: string;
  type: SignalType;
  confidence: number;
  timeframe: string;
  reason: string;
  timestamp: Date;
  market: "crypto" | "forex" | "stocks";
}

// Portfolio
export interface Asset {
  symbol: string;
  name: string;
  amount: number;
  avgBuyPrice: number;
  currentPrice: number;
  exchange: string;
}

export interface Portfolio {
  assets: Asset[];
  totalValue: number;
  totalInvested: number;
  pnl: number;
  pnlPercent: number;
  lastUpdated: Date;
}

// News
export type Sentiment = "bullish" | "bearish" | "neutral";

export interface NewsItem {
  id: string;
  title: string;
  source: string;
  url: string;
  sentiment: Sentiment;
  publishedAt: Date;
  tags: string[];
}

// Exchange connections
export interface ExchangeConnection {
  id: string;
  name: string;
  type: "cex" | "dex";
  connected: boolean;
  lastSync?: Date;
}

// Tier access config
export const TIER_LIMITS: Record<Tier, {
  signalsPerDay: number;
  portfolioAssets: number;
  aiQueriesPerDay: number;
  exchanges: number;
  vipSignals: boolean;
  webhookAccess: boolean;
  chartTools: boolean;
}> = {
  free: {
    signalsPerDay: 5,
    portfolioAssets: 3,
    aiQueriesPerDay: 0,
    exchanges: 0,
    vipSignals: false,
    webhookAccess: false,
    chartTools: false,
  },
  pro: {
    signalsPerDay: Infinity,
    portfolioAssets: Infinity,
    aiQueriesPerDay: 10,
    exchanges: 5,
    vipSignals: false,
    webhookAccess: false,
    chartTools: true,
  },
  elite: {
    signalsPerDay: Infinity,
    portfolioAssets: Infinity,
    aiQueriesPerDay: Infinity,
    exchanges: Infinity,
    vipSignals: true,
    webhookAccess: true,
    chartTools: true,
  },
};

// ─── Discord role ID → tier mapping ──────────────────────────────────────────
// Generated by tradex-setup-bot — update if you recreate roles
export const DISCORD_ROLE_TIER_MAP: Record<string, Tier> = {
  "1482205691954593844": "elite",  // 🔱 Elite VIP
  "1482205694139830333": "pro",    // ⚡ Pro
  "1482205695754375273": "free",   // 👤 Free
};